version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: median-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umcAPIContainer
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:password@postgres:5432/median-db?schema=public
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: umcPGAdminContainer
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres: